version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: kottab_postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Mahmoud_132003
      - POSTGRES_DB=kottab_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local


